export default {
  开始日期不是日期类型: 'Startdato er ikke en gyldig dato',
  结束日期不是日期类型: 'Sluttdato er ikke en gyldig dato',
  单位不合法: 'Ugyldig enhet',
  '年%04019': 'år',
  '月%04020': 'måned',
  '天%04021': 'dag',
  '时%04022': 'time',
  '分%04023': 'minutt',
  开始位置不是数字: 'Startposisjon er ikke et tall',
  结束位置不是数字: 'Sluttposisjon er ikke et tall',
  参数不是数字: 'Parameter er ikke et tall',
  被除数不是数字: 'Dividenden er ikke et tall',
  除数不是数字: 'Divisoren er ikke et tall',
  除数不能为0: 'Divisor kan ikke være 0',
  没有参数: 'Ingen parametere',
  长度太大: 'Lengden er for stor',
  重复字符不能为空: 'Gjentakelsestegn kan ikke være tomt',
  天数必须是数字: 'Antall dager må være et tall',
  日期不是日期类型: 'Verdien er ikke en gyldig dato',
  总对象数必须是非负整数: 'Totalt antall objekter må være et ikke-negativt heltall',
  选择对象数必须是非负整数: 'Antall valgte objekter må være et ikke-negativt heltall',
  选择对象数不能大于总对象数: 'Antall valgte objekter kan ikke overstige det totale antallet objekter',
};
