export default {
  开始日期不是日期类型: 'Sākuma datums nav derīgs datums',
  结束日期不是日期类型: 'Beigu datums nav derīgs datums',
  单位不合法: 'Nederīga vienība',
  '年%04019': 'gads',
  '月%04020': 'mēnesis',
  '天%04021': 'diena',
  '时%04022': 'stunda',
  '分%04023': 'minūte',
  开始位置不是数字: 'Sākuma pozīcija nav skaitlis',
  结束位置不是数字: 'Beigu pozīcija nav skaitlis',
  参数不是数字: 'Parametrs nav skaitlis',
  被除数不是数字: 'Dalāmais nav skaitlis',
  除数不是数字: 'Dalītājs nav skaitlis',
  除数不能为0: 'Dalītājs nevar būt 0',
  没有参数: 'Nav parametru',
  长度太大: 'Garums ir pārāk liels',
  重复字符不能为空: 'Atkārtotā rakstzīme nevar būt tukša',
  天数必须是数字: 'Dienu skaitam jābūt skaitlim',
  日期不是日期类型: 'Vērtība nav derīgs datums',
  总对象数必须是非负整数: 'Kopējam objektu skaitam jābūt nenegatīvam veselam skaitlim',
  选择对象数必须是非负整数: 'Atlasīto objektu skaitam jābūt nenegatīvam veselam skaitlim',
  选择对象数不能大于总对象数: 'Atlasīto objektu skaits nedrīkst pārsniegt kopējo objektu skaitu',
};
