export const MINGO_TASK_TYPE = {
  MINGDAO_HELP_ASSISTANT: 1,
  CREATE_WORKSHEET_ASSIGNMENT: 2,
  CREATE_RECORD_ASSIGNMENT: 3,
  CREATE_WORKSHEET_DATA_ASSIGNMENT: 4,
  CUSTOM_BOT: 8,
};

export const MINGO_TASK_STATUS = {
  CREATE_WORKSHEET_ASSIGNMENT_PREPARING_WORKSHEET_DESCRIPTION: 10,
  CREATE_WORKSHEET_ASSIGNMENT_BEGIN_CREATE_WORKSHEET: 11,
  CREATE_WORKSHEET_ASSIGNMENT_CREATE_WORKSHEET_SUCCESS: 12,
  CREATE_WORKSHEET_ASSIGNMENT_CREATE_WORKSHEET_WIDGETS: 20,
};
