export default {
  开始日期不是日期类型: 'Tarehe ya kuanza si tarehe halali',
  结束日期不是日期类型: 'Tarehe ya mwisho si tarehe halali',
  单位不合法: 'Kitengo si halali',
  '年%04019': 'mwaka',
  '月%04020': 'mwezi',
  '天%04021': 'siku',
  '时%04022': 'saa',
  '分%04023': 'dakika',
  开始位置不是数字: 'Nafasi ya kuanza si nambari',
  结束位置不是数字: 'Nafasi ya mwisho si nambari',
  参数不是数字: 'Kigezo si nambari',
  被除数不是数字: 'Mgawiwo si nambari',
  除数不是数字: 'Mgawanyaji si nambari',
  除数不能为0: 'Mgawanyaji hauwezi kuwa 0',
  没有参数: 'Hakuna vigezo',
  长度太大: 'Urefu ni mkubwa sana',
  重复字符不能为空: 'Herufi inayorudiwa haiwezi kuwa tupu',
  天数必须是数字: 'Idadi ya siku lazima iwe nambari',
  日期不是日期类型: 'Thamani si tarehe halali',
  总对象数必须是非负整数: 'Jumla ya idadi ya vitu lazima iwe nambari kamili isiyo hasi',
  选择对象数必须是非负整数: 'Idadi ya vitu vilivyochaguliwa lazima iwe nambari kamili isiyo hasi',
  选择对象数不能大于总对象数: 'Idadi ya vitu vilivyochaguliwa haiwezi kuzidi jumla ya idadi ya vitu',
};
