export default {
  开始日期不是日期类型: 'Startdato er ikke en gyldig dato',
  结束日期不是日期类型: 'Slutdato er ikke en gyldig dato',
  单位不合法: 'Ugyldig enhed',
  '年%04019': 'år',
  '月%04020': 'måned',
  '天%04021': 'dag',
  '时%04022': 'time',
  '分%04023': 'minut',
  开始位置不是数字: 'Startposition er ikke et tal',
  结束位置不是数字: 'Slutposition er ikke et tal',
  参数不是数字: 'Parameter er ikke et tal',
  被除数不是数字: 'Dividend er ikke et tal',
  除数不是数字: 'Divisor er ikke et tal',
  除数不能为0: 'Divisor må ikke være 0',
  没有参数: 'Ingen parametre',
  长度太大: 'Længden er for stor',
  重复字符不能为空: 'Gentaget tegn må ikke være tomt',
  天数必须是数字: 'Antallet af dage skal være et tal',
  日期不是日期类型: 'Værdi er ikke en gyldig dato',
  总对象数必须是非负整数: 'Det samlede antal objekter skal være et ikke-negativt heltal',
  选择对象数必须是非负整数: 'Antallet af valgte objekter skal være et ikke-negativt heltal',
  选择对象数不能大于总对象数: 'Antallet af valgte objekter må ikke overstige det samlede antal objekter',
};
