export default {
  开始日期不是日期类型: 'Data e fillimit nuk është një datë e vlefshme',
  结束日期不是日期类型: 'Data e mbarimit nuk është një datë e vlefshme',
  单位不合法: 'Njësi e pavlefshme',
  '年%04019': 'vit',
  '月%04020': 'muaj',
  '天%04021': 'ditë',
  '时%04022': 'orë',
  '分%04023': 'minutë',
  开始位置不是数字: 'Pozicioni i fillimit nuk është një numër',
  结束位置不是数字: 'Pozicioni i mbarimit nuk është një numër',
  参数不是数字: 'Parametri nuk është një numër',
  被除数不是数字: 'I pjesëtuari nuk është një numër',
  除数不是数字: 'Pjesëtuesi nuk është një numër',
  除数不能为0: 'Pjesëtuesi nuk mund të jetë 0',
  没有参数: 'Asnjë parametër',
  长度太大: 'Gjatësia është shumë e madhe',
  重复字符不能为空: 'Karakteri i përsëritur nuk mund të jetë bosh',
  天数必须是数字: 'Numri i ditëve duhet të jetë një numër',
  日期不是日期类型: 'Vlera nuk është një datë e vlefshme',
  总对象数必须是非负整数: 'Numri i përgjithshëm i objekteve duhet të jetë një numër i plotë jonegativ',
  选择对象数必须是非负整数: 'Numri i objekteve të zgjedhura duhet të jetë një numër i plotë jonegativ',
  选择对象数不能大于总对象数: 'Numri i objekteve të zgjedhura nuk mund të kalojë numrin e përgjithshëm të objekteve',
};
