export default {
  开始日期不是日期类型: "La date de début n'est pas une date valide",
  结束日期不是日期类型: "La date de fin n'est pas une date valide",
  单位不合法: 'Unité non valide',
  '年%04019': 'année',
  '月%04020': 'mois',
  '天%04021': 'jour',
  '时%04022': 'heure',
  '分%04023': 'minute',
  开始位置不是数字: "La position de début n'est pas un nombre",
  结束位置不是数字: "La position de fin n'est pas un nombre",
  参数不是数字: "Le paramètre n'est pas un nombre",
  被除数不是数字: "Le dividende n'est pas un nombre",
  除数不是数字: "Le diviseur n'est pas un nombre",
  除数不能为0: 'Le diviseur ne peut pas être 0',
  没有参数: 'Aucun paramètre',
  长度太大: 'La longueur est trop grande',
  重复字符不能为空: 'Le caractère de répétition ne peut pas être vide',
  天数必须是数字: 'Le nombre de jours doit être un nombre',
  日期不是日期类型: "La valeur n'est pas une date valide",
  总对象数必须是非负整数: "Le nombre total d'objets doit être un entier non négatif",
  选择对象数必须是非负整数: "Le nombre d'objets sélectionnés doit être un entier non négatif",
  选择对象数不能大于总对象数: "Le nombre d'objets sélectionnés ne peut pas dépasser le nombre total d'objets",
};
