export default {
  开始日期不是日期类型: 'Boshlanish sanasi yaroqli sana emas',
  结束日期不是日期类型: 'Tugash sanasi yaroqli sana emas',
  单位不合法: 'Yaroqsiz birlik',
  '年%04019': 'yil',
  '月%04020': 'oy',
  '天%04021': 'kun',
  '时%04022': 'soat',
  '分%04023': 'daqiqa',
  开始位置不是数字: 'Boshlanish pozitsiyasi raqam emas',
  结束位置不是数字: 'Tugash pozitsiyasi raqam emas',
  参数不是数字: 'Parametr raqam emas',
  被除数不是数字: "Bo'linuvchi raqam emas",
  除数不是数字: "Bo'luvchi raqam emas",
  除数不能为0: "Bo'luvchi 0 bo'lishi mumkin emas",
  没有参数: "Parametrlar yo'q",
  长度太大: 'Uzunlik juda katta',
  重复字符不能为空: "Takrorlanuvchi belgi bo'sh bo'lishi mumkin emas",
  天数必须是数字: "Kunlar soni raqam bo'lishi kerak",
  日期不是日期类型: 'Qiymat yaroqli sana emas',
  总对象数必须是非负整数: "Obyektlarning umumiy soni manfiy bo'lmagan butun son bo'lishi kerak",
  选择对象数必须是非负整数: "Tanlangan obyektlar soni manfiy bo'lmagan butun son bo'lishi kerak",
  选择对象数不能大于总对象数: 'Tanlangan obyektlar soni umumiy obyektlar sonidan oshmasligi kerak',
};
