export const COLORS = ['#e91e63', '#ff9800', '#4caf50', '#00bcd4', '#2196f3', '#9c27b0', '#3f51b5', '#455a64'];
export const ICONS = [
  'clear_1',
  'done_2',
  'star_3',
  'heart_4',
  'people_5',
  'people_alt_6',
  'shopping_7',
  'send_8',
  'mail_9',
  'flag_10',
  'notifications_11',
  'delete_12',
  'lightning_13',
  'thumb_up_14',
  'attach_money_15',
  'build_16',
  'edit_17',
  'cloudy_18',
  'qr_code_19',
  'photo_camera_20',
  'insert_photo_21',
  'watch_latersvg_22',
  'free_breakfast_23',
  'insect_24',
  'emoji_emotions_25',
  'emoji_objects_26',
  'help_center',
];
export const DEFAULT_BUTTON_LIST = [
  { style: 1, width: 2, explain: '', count: 5, mobileCount: 1, buttonList: [{ name: _l('添加新订单'), color: '#2196f3', icon: '' }] },
  { style: 2, width: 2, explain: '', count: 5, mobileCount: 1, buttonList: [{ name: _l('添加新客户'), color: '#2196f3', icon: '' }] },
  {
    style: 1,
    width: 2,
    explain: _l('客户'),
    count: 5,
    mobileCount: 1,
    buttonList: [
      { name: _l('添加客户'), color: '#4caf50', icon: '' },
      { name: _l('添加拜访记录'), color: '#4caf50', icon: '' },
      { name: _l('添加报表'), color: '#2196f3', icon: '' },
    ],
  },
  {
    style: 3,
    width: 1,
    explain: _l('快捷方式'),
    count: 2,
    mobileCount: 1,
    buttonList: [
      { name: _l('添加新订单'), color: '#2196f3', icon: '' },
      { name: _l('添加新客户'), color: '#2196f3', icon: '' },
      { name: _l('查看我的订单'), color: '#2196f3', icon: '' },
      { name: _l('查看我的统计'), color: '#2196f3', icon: '' },
    ],
  },
];
