// 默认表情
const defaultData = [
  [{ 'zh-Hans': '呵呵', en: 'Smile' }, 'wx_thumb.gif'],
  [{ 'zh-Hans': '哈哈', en: 'Grin' }, 'hanx_thumb.gif'],
  [{ 'zh-Hans': '泪', en: 'Sob' }, 'lei_thumb.gif'],
  [{ 'zh-Hans': '糗', en: 'Embarrassed' }, 'qiu_thumb.gif'],
  [{ 'zh-Hans': '偷笑', en: 'Chuckle' }, 'tx_thumb.gif'],
  [{ 'zh-Hans': '可爱', en: 'Joyful' }, 'ka_thumb.gif'],
  [{ 'zh-Hans': '得意', en: 'CoolGuy' }, 'dy_thumb.gif'],
  [{ 'zh-Hans': '花心', en: 'Drool' }, 'se_thumb.gif'],
  [{ 'zh-Hans': '失望', en: 'Frown' }, 'ng_thumb.gif'],
  [{ 'zh-Hans': '鼓掌', en: 'Clap' }, 'gz_thumb.gif'],
  [{ 'zh-Hans': '疑问', en: 'Shocked' }, 'yw_thumb.gif'],
  [{ 'zh-Hans': '吐', en: 'Puke' }, 'tu_thumb.gif'],
  [{ 'zh-Hans': '敲打', en: 'Hammer' }, 'qiao_thumb.gif'],
  [{ 'zh-Hans': '发怒', en: 'Angry' }, 'fn_qq.gif'],
  [{ 'zh-Hans': '奋斗', en: 'GoForIt' }, 'fd_qq.gif'],
  [{ 'zh-Hans': '害羞', en: 'Shy' }, 'hx_qq.gif'],
  [{ 'zh-Hans': '抓狂', en: 'Scream' }, 'zk_qq.gif'],
  [{ 'zh-Hans': '晕', en: 'Dizzy' }, 'yun_qq.gif'],
  [{ 'zh-Hans': '衰', en: 'Toasted' }, 'shuai_qq.gif'],
  [{ 'zh-Hans': '抱拳', en: 'Salute' }, 'bq_qq.gif'],
  [{ 'zh-Hans': '握手', en: 'Shake' }, 'handshake.gif'],
  [{ 'zh-Hans': '耶', en: 'Peace' }, 'yeah.gif'],
  [{ 'zh-Hans': 'Good', en: 'Good' }, 'good.gif'],
  [{ 'zh-Hans': '差劲', en: 'ThumbsDown' }, 'small.gif'],
  [{ 'zh-Hans': 'OK', en: 'OK' }, 'ok.gif'],
  [{ 'zh-Hans': '鞭炮', en: 'Firecracker' }, 'bp_qq.gif'],
  [{ 'zh-Hans': '钞票', en: 'Rich' }, 'money_qq.gif'],
  [{ 'zh-Hans': '吃饭', en: 'Eating' }, 'cf_qq.gif'],
  [{ 'zh-Hans': '灯泡', en: 'Light' }, 'dp_qq.gif'],
  [{ 'zh-Hans': '喝茶', en: 'Coffee' }, 'hc_qq.gif'],
  [{ 'zh-Hans': '猴', en: 'Monkey' }, 'monkey_qq.gif'],
  [{ 'zh-Hans': '熊猫', en: 'Panda' }, 'panda_qq.gif'],
  [{ 'zh-Hans': '啤酒', en: 'Beer' }, 'pj_qq.gif'],
  [{ 'zh-Hans': '闪电', en: 'Lightning' }, 'sd_qq.gif'],
  [{ 'zh-Hans': '双喜', en: 'Blessing' }, 'sx_qq.gif'],
  [{ 'zh-Hans': '雪花', en: 'Snowflake' }, 'xh_qq.gif'],
  [{ 'zh-Hans': '夜晚', en: 'Moon' }, 'yw_qq.gif'],
  [{ 'zh-Hans': '拥抱', en: 'Hug' }, 'yb_qq.gif'],
  [{ 'zh-Hans': '蛋糕', en: 'Cake' }, 'cake.gif'],
  [{ 'zh-Hans': '心', en: 'Heart' }, 'heart.gif'],
  [{ 'zh-Hans': '心碎', en: 'BrokenHeart' }, 'unheart.gif'],
  [{ 'zh-Hans': '玫瑰', en: 'Rose' }, 'rose.gif'],
  [{ 'zh-Hans': '礼物', en: 'Gift' }, 'gift.gif'],
  [{ 'zh-Hans': '太阳', en: 'Sun' }, 'sun.gif'],
  [{ 'zh-Hans': '威武', en: 'Awesome' }, 'vw_thumb.gif'],
  [{ 'zh-Hans': 'I LOVE MY TEAM', en: 'I LOVE MY TEAM' }, 'team.gif'],
];

// 熊
const bearData = [
  [{ 'zh-Hans': 'x 嗨', en: 'x Hello' }, '01.png'],
  [{ 'zh-Hans': 'x 哈哈', en: 'x Haha' }, '02.png'],
  [{ 'zh-Hans': 'x 害羞', en: 'x Shy' }, '03.png'],
  [{ 'zh-Hans': 'x 傲娇', en: 'x Tsundere' }, '04.png'],
  [{ 'zh-Hans': 'x 得意', en: 'x Smug' }, '05.png'],
  [{ 'zh-Hans': 'x 偷笑', en: 'x Chuckle' }, '06.png'],
  [{ 'zh-Hans': 'x 酷', en: 'x Cool' }, '07.png'],
  [{ 'zh-Hans': 'x 奔泪', en: 'x Sob' }, '08.png'],
  [{ 'zh-Hans': 'x 可怜', en: 'x Whimpe' }, '09.png'],
  [{ 'zh-Hans': 'x 花心', en: 'x Drool' }, '10.png'],
  [{ 'zh-Hans': 'x 加油', en: 'x Fighting' }, '11.png'],
  [{ 'zh-Hans': 'x 怀疑', en: 'x Skeptical' }, '12.png'],
  [{ 'zh-Hans': 'x 囧', en: 'x Speachless' }, '13.png'],
  [{ 'zh-Hans': 'x 灵感', en: 'x Inspired' }, '14.png'],
  [{ 'zh-Hans': 'x 牛逼', en: 'x Awesome' }, '15.png'],
  [{ 'zh-Hans': 'x 生气', en: 'x Angry' }, '16.png'],
  [{ 'zh-Hans': 'x 纳尼', en: 'x What' }, '17.png'],
  [{ 'zh-Hans': 'x 恶心', en: 'x Puke' }, '18.png'],
  [{ 'zh-Hans': 'x 流汗', en: 'x Sweats' }, '19.png'],
  [{ 'zh-Hans': 'x 疑问', en: 'x Confused' }, '20.png'],
  [{ 'zh-Hans': 'x 郁闷', en: 'x Let Down' }, '21.png'],
  [{ 'zh-Hans': 'x 晕', en: 'x Dizzy' }, '22.png'],
  [{ 'zh-Hans': 'x 震惊', en: 'x Shocked' }, '23.png'],
  [{ 'zh-Hans': 'x I LOVE MY TEAM', en: 'x I LOVE MY TEAM' }, '24.png'],
];
// emoji 表情
const emojiData = {};

emojiData[0] = {
  name: 'Smileys & People',
  content: [
    '😀',
    '😁',
    '😂',
    '😃',
    '😄',
    '😅',
    '😆',
    '😉',
    '😊',
    '😋',
    '😎',
    '😍',
    '😘',
    '😗',
    '😙',
    '😚',
    '☺',
    '😇',
    '😐',
    '😑',
    '😶',
    '😏',
    '😣',
    '😥',
    '😮',
    '😯',
    '😪',
    '😫',
    '😴',
    '😌',
    '😛',
    '😜',
    '😝',
    '😒',
    '😓',
    '😔',
    '😕',
    '😲',
    '😷',
    '😖',
    '😞',
    '😟',
    '😤',
    '😢',
    '😭',
    '😦',
    '😧',
    '😨',
    '😩',
    '😬',
    '😰',
    '😱',
    '😳',
    '😵',
    '😡',
    '😠',
    '😈',
    '👿',
    '👹',
    '👺',
    '💀',
    '👻',
    '👽',
    '💩',
    '😺',
    '😸',
    '😹',
    '😻',
    '😼',
    '😽',
    '🙀',
    '😿',
    '😾',
    '👦',
    '👧',
    '👨',
    '👩',
    '👴',
    '👵',
    '👶',
    '👱',
    '👮',
    '👲',
    '👳',
    '👷',
    '👸',
    '💂',
    '🎅',
    '👰',
    '👼',
    '💆',
    '💇',
    '🙍',
    '🙎',
    '🙅',
    '🙆',
    '💁',
    '🙋',
    '🙇',
    '🙌',
    '🙏',
    '👤',
    '👥',
    '🚶',
    '🏃',
    '👯',
    '💃',
    '💪',
    '👈',
    '👉',
    '☝',
    '👆',
    '👇',
    '✌',
    '✋',
    '👌',
    '👍',
    '👎',
    '✊',
    '👊',
    '👋',
    '👏',
    '👐',
    '💅',
    '👂',
    '👃',
    '👣',
    '👀',
    '👅',
    '👄',
    '💋',
    '👓',
    '👔',
    '👕',
    '👖',
    '👗',
    '👘',
    '👙',
    '👚',
    '👛',
    '👜',
    '👝',
    '🎒',
    '👞',
    '👟',
    '👠',
    '👡',
    '👢',
    '👑',
    '👒',
    '🎩',
    '🎓',
    '💄',
    '💍',
    '🌂',
    '💼',
    '👫',
    '👬',
    '👭',
    '💏',
    '💑',
    '👪',
  ],
};

emojiData[1] = {
  name: 'Animal & Nature',
  content: [
    '🙈',
    '🙉',
    '🙊',
    '🐵',
    '🐒',
    '🐶',
    '🐕',
    '🐩',
    '🐺',
    '🐱',
    '🐈',
    '🐯',
    '🐅',
    '🐆',
    '🐴',
    '🐎',
    '🐮',
    '🐂',
    '🐃',
    '🐄',
    '🐷',
    '🐖',
    '🐗',
    '🐽',
    '🐏',
    '🐑',
    '🐐',
    '🐪',
    '🐫',
    '🐘',
    '🐭',
    '🐁',
    '🐀',
    '🐹',
    '🐰',
    '🐇',
    '🐻',
    '🐨',
    '🐼',
    '🐾',
    '🐔',
    '🐓',
    '🐣',
    '🐤',
    '🐥',
    '🐦',
    '🐧',
    '🐸',
    '🐊',
    '🐢',
    '🐍',
    '🐲',
    '🐉',
    '🐳',
    '🐋',
    '🐬',
    '🐟',
    '🐠',
    '🐡',
    '🐙',
    '🐚',
    '🐌',
    '🐛',
    '🐜',
    '🐝',
    '🐞',
    '💐',
    '🌸',
    '💮',
    '🌹',
    '🌺',
    '🌻',
    '🌼',
    '🌷',
    '🌱',
    '🌲',
    '🌳',
    '🌴',
    '🌵',
    '🌾',
    '🌿',
    '🍀',
    '🍁',
    '🍂',
    '🍃',
    '🌍',
    '🌎',
    '🌏',
    '🌐',
    '🌑',
    '🌒',
    '🌓',
    '🌔',
    '🌕',
    '🌖',
    '🌗',
    '🌘',
    '🌙',
    '🌚',
    '🌛',
    '🌜',
    '☀',
    '🌝',
    '🌞',
    '⭐',
    '🌟',
    '🌠',
    '☁',
    '⛅',
    '💦',
    '💨',
    '☔',
    '⚡',
    '❄',
    '🔥',
    '💧',
    '🌊',
  ],
};

emojiData[2] = {
  name: 'Food & Drink',
  content: [
    '🍇',
    '🍈',
    '🍉',
    '🍊',
    '🍋',
    '🍌',
    '🍍',
    '🍎',
    '🍏',
    '🍐',
    '🍑',
    '🍒',
    '🍓',
    '🍅',
    '🍆',
    '🌽',
    '🍄',
    '🌰',
    '🍞',
    '🍖',
    '🍗',
    '🍔',
    '🍟',
    '🍕',
    '🍳',
    '🍲',
    '🍱',
    '🍘',
    '🍙',
    '🍚',
    '🍛',
    '🍜',
    '🍝',
    '🍠',
    '🍢',
    '🍣',
    '🍤',
    '🍥',
    '🍡',
    '🍦',
    '🍧',
    '🍨',
    '🍩',
    '🍪',
    '🎂',
    '🍰',
    '🍫',
    '🍬',
    '🍭',
    '🍮',
    '🍯',
    '🍼',
    '☕',
    '🍵',
    '🍶',
    '🍷',
    '🍸',
    '🍹',
    '🍺',
    '🍻',
    '🍴',
  ],
};

emojiData[3] = {
  name: 'Objects',
  content: [
    '💌',
    '💣',
    '💎',
    '🔪',
    '💈',
    '🚪',
    '🚽',
    '🚿',
    '🛁',
    '⌛',
    '⌚',
    '🎈',
    '🎉',
    '🎊',
    '🎎',
    '🎏',
    '🎐',
    '🎀',
    '🎁',
    '📯',
    '📻',
    '📱',
    '📲',
    '☎',
    '📞',
    '📟',
    '📠',
    '🔋',
    '🔌',
    '💻',
    '💽',
    '💾',
    '💿',
    '📀',
    '🎥',
    '📺',
    '📷',
    '📹',
    '📼',
    '🔍',
    '🔎',
    '🔬',
    '🔭',
    '📡',
    '💡',
    '🔦',
    '🏮',
    '📔',
    '📕',
    '📖',
    '📗',
    '📘',
    '📙',
    '📚',
    '📓',
    '📃',
    '📜',
    '📄',
    '📰',
    '📑',
    '🔖',
    '💰',
    '💴',
    '💵',
    '💶',
    '💷',
    '💸',
    '💳',
    '✉',
    '📧',
    '📨',
    '📩',
    '📤',
    '📥',
    '📦',
    '📫',
    '📪',
    '📬',
    '📭',
    '📮',
    '✏',
    '✒',
    '📝',
    '📁',
    '📂',
    '📅',
    '📆',
    '📇',
    '📈',
    '📉',
    '📊',
    '📋',
    '📌',
    '📍',
    '📎',
    '📏',
    '📐',
    '✂',
    '🔒',
    '🔓',
    '🔏',
    '🔐',
    '🔑',
    '🔨',
    '🔫',
    '🔧',
    '🔩',
    '🔗',
    '💉',
    '💊',
    '🚬',
    '🗿',
    '🔮',
    '🚩',
    '🎌',
    '🏴',
    '🏳',
    '🏖',
  ],
};

const AruData = [
  [null, '01.png'],
  [null, '02.png'],
  [null, '03.png'],
  [null, '04.png'],
  [null, '05.png'],
  [null, '06.png'],
  [null, '07.png'],
  [null, '08.png'],
  [null, '09.png'],
  [null, '10.png'],
  [null, '11.png'],
  [null, '12.png'],
  [null, '13.png'],
  [null, '14.png'],
  [null, '15.png'],
  [null, '16.png'],
  [null, '17.png'],
  [null, '18.png'],
  [null, '19.png'],
  [null, '20.png'],
  [null, '21.png'],
  [null, '22.png'],
  [null, '23.png'],
  [null, '24.png'],
  [null, '25.png'],
  [null, '26.png'],
  [null, '27.png'],
  [null, '28.png'],
  [null, '29.png'],
  [null, '30.png'],
  [null, '31.png'],
  [null, '32.png'],
  [null, '33.png'],
  [null, '34.png'],
  [null, '35.png'],
  [null, '36.png'],
  [null, '37.png'],
  [null, '38.png'],
  [null, '39.png'],
  [null, '40.png'],
  [null, '41.png'],
  [null, '42.png'],
  [null, '43.png'],
  [null, '44.png'],
  [null, '45.png'],
  [null, '46.png'],
  [null, '47.png'],
  [null, '48.png'],
  [null, '49.png'],
  [null, '50.png'],
  [null, '51.png'],
  [null, '52.png'],
  [null, '53.png'],
  [null, '54.png'],
  [null, '55.png'],
  [null, '56.png'],
  [null, '57.png'],
  [null, '58.png'],
  [null, '59.png'],
  [null, '60.png'],
  [null, '61.png'],
  [null, '62.png'],
  [null, '63.png'],
  [null, '64.png'],
  [null, '65.png'],
  [null, '66.png'],
  [null, '67.png'],
  [null, '68.png'],
  [null, '69.png'],
  [null, '70.png'],
  [null, '71.png'],
  [null, '72.png'],
  [null, '73.png'],
  [null, '74.png'],
  [null, '75.png'],
  [null, '76.png'],
  [null, '77.png'],
  [null, '78.png'],
  [null, '79.png'],
  [null, '80.png'],
  [null, '81.png'],
  [null, '82.png'],
  [null, '83.png'],
  [null, '84.png'],
  [null, '85.png'],
  [null, '86.png'],
  [null, '87.png'],
  [null, '88.png'],
  [null, '89.png'],
  [null, '90.png'],
];

export const EMOTION_GROUP_IDS = {
  HISTORY: 'history',
  CLASSIC: 'classic',
  PEOPLE: 'people',
  NATURE: 'nature',
  FOOD: 'food',
  OBJECTS: 'objects',
  BEAR: 'bear',
  ARU: 'aru',
};

export const EMOTION_IMAGE_BASE = '/staticfiles/images/emotion/';

const getCurrentLanguage = () =>
  typeof window !== 'undefined' && typeof window.getCurrentLang === 'function' && window.getCurrentLang() === 'zh-Hans'
    ? 'zh-Hans'
    : 'en';

const getLocalizedKey = key => (key && typeof key === 'object' ? key[getCurrentLanguage()] : key);

const createImageItems = (groupId, items) =>
  items.map(([originalKey, img]) => ({
    id: `${groupId}:${img}`,
    groupId,
    code: getLocalizedKey(originalKey),
    originalKey,
    img,
  }));

const createEmojiItems = (groupId, items) =>
  items.map(code => ({
    id: `${groupId}:${code}`,
    groupId,
    code,
    originalKey: code,
  }));

const createParseItems = items => items.map(([originalKey, img]) => ({ originalKey, img }));

export const emotionParseGroups = [
  {
    id: EMOTION_GROUP_IDS.CLASSIC,
    path: 'default/',
    showRetina: true,
    size: 24,
    itemClassName: 'emotion-default',
    content: createParseItems(defaultData),
  },
  {
    id: EMOTION_GROUP_IDS.BEAR,
    path: 'bear/',
    itemClassName: 'emotion-default',
    content: createParseItems(bearData),
  },
  {
    id: EMOTION_GROUP_IDS.ARU,
    path: 'aru/',
    itemClassName: 'emotion-default',
    content: createParseItems(AruData),
  },
];

/**
 * 在实际渲染或解析时生成数据，避免模块加载阶段固化语言。
 */
export function getEmotionGroups() {
  return [
    {
      id: EMOTION_GROUP_IDS.HISTORY,
      label: _l('历史'),
      imageName: 'history',
      type: 'history',
      content: [],
    },
    {
      id: EMOTION_GROUP_IDS.CLASSIC,
      label: _l('经典表情'),
      imageName: 'default',
      type: 'classic',
      path: 'default/',
      showRetina: true,
      size: 24,
      itemClassName: 'emotion-default',
      content: createImageItems(EMOTION_GROUP_IDS.CLASSIC, defaultData),
    },
    {
      id: EMOTION_GROUP_IDS.PEOPLE,
      label: _l('人物'),
      imageName: 'smileys',
      type: 'emoji',
      size: 24,
      content: createEmojiItems(EMOTION_GROUP_IDS.PEOPLE, emojiData[0].content),
    },
    {
      id: EMOTION_GROUP_IDS.NATURE,
      label: _l('动物和大自然'),
      imageName: 'animals',
      type: 'emoji',
      size: 24,
      content: createEmojiItems(EMOTION_GROUP_IDS.NATURE, emojiData[1].content),
    },
    {
      id: EMOTION_GROUP_IDS.FOOD,
      label: _l('食物和饮料'),
      imageName: 'foods',
      type: 'emoji',
      size: 24,
      content: createEmojiItems(EMOTION_GROUP_IDS.FOOD, emojiData[2].content),
    },
    {
      id: EMOTION_GROUP_IDS.OBJECTS,
      label: _l('物体'),
      imageName: 'objects',
      type: 'emoji',
      size: 24,
      content: createEmojiItems(EMOTION_GROUP_IDS.OBJECTS, emojiData[3].content),
    },
    {
      id: EMOTION_GROUP_IDS.BEAR,
      label: _l('笨笨熊'),
      imageName: 'bear',
      type: 'sticker',
      path: 'bear/',
      itemClassName: 'emotion-default',
      content: createImageItems(EMOTION_GROUP_IDS.BEAR, bearData),
    },
    {
      id: EMOTION_GROUP_IDS.ARU,
      label: 'Aru',
      imageName: 'aru',
      type: 'sticker',
      path: 'aru/',
      itemClassName: 'emotion-default',
      content: createImageItems(EMOTION_GROUP_IDS.ARU, AruData),
    },
  ];
}

export function getEmotionAliases(item) {
  if (!item || !item.originalKey) return [];

  return typeof item.originalKey === 'object'
    ? [...new Set(Object.values(item.originalKey).filter(Boolean))]
    : [item.originalKey];
}

export function getEmotionImageSrc(group, item, { animated = false } = {}) {
  if (!group || !item || !item.img) return '';

  const useRetina =
    group.showRetina && typeof window !== 'undefined' && window.devicePixelRatio && window.devicePixelRatio > 1;
  const imageName = animated && group.id === EMOTION_GROUP_IDS.BEAR ? item.img.replace(/\.png$/i, '.gif') : item.img;

  return `${EMOTION_IMAGE_BASE}${group.path}${useRetina ? 'retina/' : ''}${imageName}`;
}
