export default {
  开始日期不是日期类型: 'Ngày bắt đầu không phải là ngày hợp lệ',
  结束日期不是日期类型: 'Ngày kết thúc không phải là ngày hợp lệ',
  单位不合法: 'Đơn vị không hợp lệ',
  '年%04019': 'năm',
  '月%04020': 'tháng',
  '天%04021': 'ngày',
  '时%04022': 'giờ',
  '分%04023': 'phút',
  开始位置不是数字: 'Vị trí bắt đầu không phải là số',
  结束位置不是数字: 'Vị trí kết thúc không phải là số',
  参数不是数字: 'Tham số không phải là số',
  被除数不是数字: 'Số bị chia không phải là số',
  除数不是数字: 'Số chia không phải là số',
  除数不能为0: 'Số chia không thể bằng 0',
  没有参数: 'Không có tham số',
  长度太大: 'Độ dài quá lớn',
  重复字符不能为空: 'Ký tự lặp lại không thể trống',
  天数必须是数字: 'Số ngày phải là số',
  日期不是日期类型: 'Giá trị không phải là ngày hợp lệ',
  总对象数必须是非负整数: 'Tổng số đối tượng phải là số nguyên không âm',
  选择对象数必须是非负整数: 'Số đối tượng được chọn phải là số nguyên không âm',
  选择对象数不能大于总对象数: 'Số đối tượng được chọn không thể vượt quá tổng số đối tượng',
};
