export const SCOPES = {
  200000: _l('用户'),
  200100: _l('获取用户所在组织列表'),
  200200: _l('获取用户信息'),

  10000: _l('应用管理'),
  10500: _l('获取应用列表'),
  10400: _l('获取应用信息'),
  10100: _l('创建应用'),
  10600: _l('创建应用项分组'),
  10700: _l('批量创建应用项'),
  10200: _l('编辑应用'),
  10300: _l('删除应用'),

  20000: _l('工作表'),
  20500: _l('获取工作表列表'),
  20400: _l('获取工作表详情'),
  20100: _l('创建工作表'),
  20200: _l('编辑工作表'),
  20300: _l('删除工作表'),

  30000: _l('行记录'),
  30100: _l('获取行记录详情'),
  30200: _l('创建行记录'),
  30300: _l('更新行记录'),
  30400: _l('删除行记录'),
  30500: _l('获取行记录列表'),
  30600: _l('批量创建记录'),
  30700: _l('批量更新记录'),
  30800: _l('批量删除记录'),
  30900: _l('获取记录讨论'),
  31000: _l('获取记录日志'),
  31100: _l('获取透视表数据'),
  31200: _l('获取记录关联关系'),
  31300: _l('获取记录分享链接'),

  140000: _l('视图'),
  140100: _l('创建视图'),

  130000: _l('统计图'),
  130100: _l('新建统计图'),

  120000: _l('自定义页面'),
  120100: _l('编辑自定义页面'),

  70000: _l('工作流'),
  70200: _l('获取触发流程列表'),
  70100: _l('获取触发流程详情'),
  70300: _l('触发工作流'),
  71100: _l('获取工作流结构'),
  70400: _l('获取审批流程执行列表'),
  70500: _l('获取审批流程执行详情'),
  70600: _l('创建工作流'),
  70700: _l('批量创建工作流节点'),
  70800: _l('校验工作流'),
  71200: _l('发布工作流'),
  70900: _l('删除工作流节点'),
  71000: _l('删除工作流'),

  150000: _l('流程待办'),
  150100: _l('获取用户流程待办列表'),
  150200: _l('获取审批待办详情'),
  150300: _l('批量审批'),
  150400: _l('撤销'),
  150500: _l('退回'),
  150600: _l('中止'),
  150700: _l('催办'),

  90000: _l('对话机器人'),
  90100: _l('创建对话机器人'),

  110000: _l('自定义动作'),
  // 110100: _l('获取自定义动作列表'),
  // 110200: _l('获取自定义动作详情'),
  110300: _l('批量创建自定义动作'),
  // 110400: _l('更新自定义动作'),
  // 110500: _l('删除自定义动作'),

  60000: _l('角色'),
  60100: _l('删除角色'),
  60200: _l('获取角色详情'),
  60300: _l('成员退出所有角色'),
  60400: _l('获取角色列表'),
  60500: _l('角色移除成员'),
  60600: _l('角色添加成员'),
  60700: _l('创建角色'),

  40000: _l('选项集'),
  40100: _l('创建选项'),
  40200: _l('删除选项'),
  40300: _l('获取选项列表'),
  40400: _l('更新选项'),

  80000: _l('向量知识库'),
  80100: _l('获取向量知识库列表'),
  80200: _l('向量知识库检索'),

  50000: _l('组织'),
  50100: _l('查找组织部门'),
  50200: _l('查找组织成员'),
  50300: _l('获取区域信息'),
};

export const SCOPE_LIST = [
  {
    code: 200000,
    key: '',
    checked: true,
    children: [
      {
        code: 200100,
        key: 'org:list',
        checked: true,
        children: [],
      },
      {
        code: 200200,
        key: 'user:me',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 10000,
    key: '',
    checked: true,
    children: [
      {
        code: 10500,
        key: 'app:list',
        checked: true,
        children: [],
      },
      {
        code: 10400,
        key: 'app:get',
        checked: true,
        children: [],
      },
      {
        code: 10100,
        key: 'app:create',
        checked: true,
        children: [],
      },
      {
        code: 10600,
        key: 'app:create_section',
        checked: true,
        children: [],
      },
      {
        code: 10700,
        key: 'app:batch_create_item',
        checked: true,
        children: [],
      },
      {
        code: 10200,
        key: 'app:edit',
        checked: true,
        children: [],
      },
      {
        code: 10300,
        key: 'app:delete',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 20000,
    key: '',
    checked: true,
    children: [
      {
        code: 20500,
        key: 'worksheet:list',
        checked: true,
        children: [],
      },
      {
        code: 20400,
        key: 'worksheet:get',
        checked: true,
        children: [],
      },
      {
        code: 20100,
        key: 'worksheet:create',
        checked: true,
        children: [],
      },
      {
        code: 20200,
        key: 'worksheet:edit',
        checked: true,
        children: [],
      },
      {
        code: 20300,
        key: 'worksheet:delete',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 30000,
    key: '',
    checked: true,
    children: [
      {
        code: 30100,
        key: 'record:get',
        checked: true,
        children: [],
      },
      {
        code: 30200,
        key: 'record:create',
        checked: true,
        children: [],
      },
      {
        code: 30300,
        key: 'record:edit',
        checked: true,
        children: [],
      },
      {
        code: 30400,
        key: 'record:delete',
        checked: true,
        children: [],
      },
      {
        code: 30500,
        key: 'record:list',
        checked: true,
        children: [],
      },
      {
        code: 30600,
        key: 'record:batch_create',
        checked: true,
        children: [],
      },
      {
        code: 30700,
        key: 'record:batch_update',
        checked: true,
        children: [],
      },
      {
        code: 30800,
        key: 'record:batch_delete',
        checked: true,
        children: [],
      },
      {
        code: 30900,
        key: 'record:get_discussions',
        checked: true,
        children: [],
      },
      {
        code: 31000,
        key: 'record:get_logs',
        checked: true,
        children: [],
      },
      {
        code: 31100,
        key: 'record:get_pivot',
        checked: true,
        children: [],
      },
      {
        code: 31200,
        key: 'record:get_relations',
        checked: true,
        children: [],
      },
      {
        code: 31300,
        key: 'record:get_share_link',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 60000,
    key: '',
    checked: true,
    children: [
      {
        code: 60100,
        key: 'role:delete',
        checked: true,
        children: [],
      },
      {
        code: 60200,
        key: 'role:get',
        checked: true,
        children: [],
      },
      {
        code: 60300,
        key: 'role:leave_all',
        checked: true,
        children: [],
      },
      {
        code: 60400,
        key: 'role:list',
        checked: true,
        children: [],
      },
      {
        code: 60500,
        key: 'role:remove_member',
        checked: true,
        children: [],
      },
      {
        code: 60600,
        key: 'role:add_member',
        checked: true,
        children: [],
      },
      {
        code: 60700,
        key: 'role:create',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 40000,
    key: '',
    checked: true,
    children: [
      {
        code: 40300,
        key: 'options:list',
        checked: true,
        children: [],
      },
      {
        code: 40100,
        key: 'options:create',
        checked: true,
        children: [],
      },
      {
        code: 40200,
        key: 'options:delete',
        checked: true,
        children: [],
      },
      {
        code: 40400,
        key: 'options:update',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 70000,
    key: '',
    checked: true,
    children: [
      {
        code: 70200,
        key: 'process:list',
        checked: true,
        children: [],
      },
      {
        code: 70100,
        key: 'process:get',
        checked: true,
        children: [],
      },
      {
        code: 70300,
        key: 'process:trigger',
        checked: true,
        children: [],
      },
      {
        code: 71100,
        key: 'workflow:get',
        checked: true,
        children: [],
      },
      {
        code: 70400,
        key: 'workflow:get_approval_executions',
        checked: true,
        children: [],
      },
      {
        code: 70500,
        key: 'workflow:get_approval_execution',
        checked: true,
        children: [],
      },
      {
        code: 70600,
        key: 'workflow:create',
        checked: true,
        children: [],
      },
      {
        code: 70700,
        key: 'workflow:batch_create_nodes',
        checked: true,
        children: [],
      },
      {
        code: 70800,
        key: 'workflow:validate',
        checked: true,
        children: [],
      },
      {
        code: 71200,
        key: 'workflow:publish',
        checked: true,
        children: [],
      },
      {
        code: 70900,
        key: 'workflow:delete_node',
        checked: true,
        children: [],
      },
      {
        code: 71000,
        key: 'workflow:delete',
        checked: true,
        children: [],
      },
    ],
  },

  {
    code: 150000,
    key: '',
    checked: true,
    children: [
      {
        code: 150100,
        key: 'approval:list',
        checked: true,
        children: [],
      },
      {
        code: 150200,
        key: 'approval:get',
        checked: true,
        children: [],
      },
      {
        code: 150300,
        key: 'approval:batch',
        checked: true,
        children: [],
      },
      {
        code: 150400,
        key: 'approval:revoke',
        checked: true,
        children: [],
      },
      {
        code: 150500,
        key: 'approval:return',
        checked: true,
        children: [],
      },
      {
        code: 150600,
        key: 'approval:terminate',
        checked: true,
        children: [],
      },
      {
        code: 150700,
        key: 'approval:urge',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 80000,
    key: '',
    checked: true,
    children: [
      {
        code: 80100,
        key: 'knowledge:list',
        checked: true,
        children: [],
      },
      {
        code: 80200,
        key: 'knowledge:search',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 90000,
    key: '',
    checked: true,
    children: [
      {
        code: 90100,
        key: 'chatbot:create',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 110000,
    key: '',
    checked: true,
    children: [
      // {
      //   code: 110100,
      //   key: 'custom_action:list',
      //   checked: true,
      //   children: [],
      // },
      // {
      //   code: 110200,
      //   key: 'custom_action:get',
      //   checked: true,
      //   children: [],
      // },
      {
        code: 110300,
        key: 'custom_action:batch_create',
        checked: true,
        children: [],
      },
      // {
      //   code: 110400,
      //   key: 'custom_action:edit',
      //   checked: true,
      //   children: [],
      // },
      // {
      //   code: 110500,
      //   key: 'custom_action:delete',
      //   checked: true,
      //   children: [],
      // },
    ],
  },
  {
    code: 140000,
    key: '',
    checked: true,
    children: [
      {
        code: 140100,
        key: 'view:create',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 130000,
    key: '',
    checked: true,
    children: [
      {
        code: 130100,
        key: 'chart:create',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 120000,
    key: '',
    checked: true,
    children: [
      {
        code: 120100,
        key: 'custom_page:edit',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 50000,
    key: '',
    checked: true,
    children: [
      {
        code: 50100,
        key: 'public:find_department',
        checked: true,
        children: [],
      },
      {
        code: 50200,
        key: 'public:find_member',
        checked: true,
        children: [],
      },
      {
        code: 50300,
        key: 'public:get_regions',
        checked: true,
        children: [],
      },
    ],
  },
];
