export default {
  开始日期不是日期类型: 'Začetni datum ni veljaven datum',
  结束日期不是日期类型: 'Končni datum ni veljaven datum',
  单位不合法: 'Neveljavna enota',
  '年%04019': 'leto',
  '月%04020': 'mesec',
  '天%04021': 'dan',
  '时%04022': 'ura',
  '分%04023': 'minuta',
  开始位置不是数字: 'Začetni položaj ni številka',
  结束位置不是数字: 'Končni položaj ni številka',
  参数不是数字: 'Parameter ni številka',
  被除数不是数字: 'Deljenec ni številka',
  除数不是数字: 'Delitelj ni številka',
  除数不能为0: 'Delitelj ne more biti 0',
  没有参数: 'Brez parametrov',
  长度太大: 'Dolžina je prevelika',
  重复字符不能为空: 'Ponavljajoči se znak ne sme biti prazen',
  天数必须是数字: 'Število dni mora biti številka',
  日期不是日期类型: 'Vrednost ni veljaven datum',
  总对象数必须是非负整数: 'Skupno število objektov mora biti nenegativno celo število',
  选择对象数必须是非负整数: 'Število izbranih objektov mora biti nenegativno celo število',
  选择对象数不能大于总对象数: 'Število izbranih objektov ne sme presegati skupnega števila objektov',
};
