export default {
  开始日期不是日期类型: 'Tanggal mulai bukan tanggal yang valid',
  结束日期不是日期类型: 'Tanggal akhir bukan tanggal yang valid',
  单位不合法: 'Unit tidak valid',
  '年%04019': 'tahun',
  '月%04020': 'bulan',
  '天%04021': 'hari',
  '时%04022': 'jam',
  '分%04023': 'menit',
  开始位置不是数字: 'Posisi awal bukan angka',
  结束位置不是数字: 'Posisi akhir bukan angka',
  参数不是数字: 'Parameter bukan angka',
  被除数不是数字: 'Bilangan yang dibagi bukan angka',
  除数不是数字: 'Pembagi bukan angka',
  除数不能为0: 'Pembagi tidak boleh 0',
  没有参数: 'Tidak ada parameter',
  长度太大: 'Panjang terlalu besar',
  重复字符不能为空: 'Karakter berulang tidak boleh kosong',
  天数必须是数字: 'Jumlah hari harus berupa angka',
  日期不是日期类型: 'Nilai bukan tanggal yang valid',
  总对象数必须是非负整数: 'Jumlah total objek harus bilangan bulat non-negatif',
  选择对象数必须是非负整数: 'Jumlah objek yang dipilih harus bilangan bulat non-negatif',
  选择对象数不能大于总对象数: 'Jumlah objek yang dipilih tidak boleh melebihi jumlah total objek',
};
