export default {
  开始日期不是日期类型: 'Upphafsdagsetning er ekki gild dagsetning',
  结束日期不是日期类型: 'Lokadagsetning er ekki gild dagsetning',
  单位不合法: 'Ógild eining',
  '年%04019': 'ár',
  '月%04020': 'mánuður',
  '天%04021': 'dagur',
  '时%04022': 'klukkustund',
  '分%04023': 'mínúta',
  开始位置不是数字: 'Upphafsstaða er ekki tala',
  结束位置不是数字: 'Lokastaða er ekki tala',
  参数不是数字: 'Færibreyta er ekki tala',
  被除数不是数字: 'Deilistofninn er ekki tala',
  除数不是数字: 'Deilirinn er ekki tala',
  除数不能为0: 'Deilir má ekki vera 0',
  没有参数: 'Engar færibreytur',
  长度太大: 'Lengdin er of stór',
  重复字符不能为空: 'Endurtekinn stafur má ekki vera tómur',
  天数必须是数字: 'Fjöldi daga verður að vera tala',
  日期不是日期类型: 'Gildi er ekki gild dagsetning',
  总对象数必须是非负整数: 'Heildarfjöldi hluta verður að vera ónegatíf heiltala',
  选择对象数必须是非负整数: 'Fjöldi valinna hluta verður að vera ónegatíf heiltala',
  选择对象数不能大于总对象数: 'Fjöldi valinna hluta má ekki vera meiri en heildarfjöldi hluta',
};
