export default {
  开始日期不是日期类型: 'A data de início não é uma data válida',
  结束日期不是日期类型: 'A data final não é uma data válida',
  单位不合法: 'Unidade inválida',
  '年%04019': 'ano',
  '月%04020': 'mês',
  '天%04021': 'dia',
  '时%04022': 'hora',
  '分%04023': 'minuto',
  开始位置不是数字: 'A posição inicial não é um número',
  结束位置不是数字: 'A posição final não é um número',
  参数不是数字: 'O parâmetro não é um número',
  被除数不是数字: 'O dividendo não é um número',
  除数不是数字: 'O divisor não é um número',
  除数不能为0: 'O divisor não pode ser 0',
  没有参数: 'Sem parâmetros',
  长度太大: 'O comprimento é muito grande',
  重复字符不能为空: 'O caractere de repetição não pode estar vazio',
  天数必须是数字: 'O número de dias deve ser um número',
  日期不是日期类型: 'O valor não é uma data válida',
  总对象数必须是非负整数: 'O número total de objetos deve ser um inteiro não negativo',
  选择对象数必须是非负整数: 'O número de objetos selecionados deve ser um inteiro não negativo',
  选择对象数不能大于总对象数: 'O número de objetos selecionados não pode exceder o número total de objetos',
};
