export default {
  开始日期不是日期类型: 'Početni datum nije valjan datum',
  结束日期不是日期类型: 'Završni datum nije valjan datum',
  单位不合法: 'Nevažeća jedinica',
  '年%04019': 'godina',
  '月%04020': 'mjesec',
  '天%04021': 'dan',
  '时%04022': 'sat',
  '分%04023': 'minuta',
  开始位置不是数字: 'Početna pozicija nije broj',
  结束位置不是数字: 'Završna pozicija nije broj',
  参数不是数字: 'Parametar nije broj',
  被除数不是数字: 'Djeljenik nije broj',
  除数不是数字: 'Djelitelj nije broj',
  除数不能为0: 'Djelitelj ne može biti 0',
  没有参数: 'Nema parametara',
  长度太大: 'Duljina je prevelika',
  重复字符不能为空: 'Ponavljajući znak ne može biti prazan',
  天数必须是数字: 'Broj dana mora biti broj',
  日期不是日期类型: 'Vrijednost nije valjan datum',
  总对象数必须是非负整数: 'Ukupan broj objekata mora biti nenegativan cijeli broj',
  选择对象数必须是非负整数: 'Broj odabranih objekata mora biti nenegativan cijeli broj',
  选择对象数不能大于总对象数: 'Broj odabranih objekata ne može premašiti ukupan broj objekata',
};
