export const SCOPES = {
  10000: _l('应用'),
  10500: _l('获取应用列表'),
  10100: _l('创建应用'),
  10200: _l('编辑应用'),
  10300: _l('删除应用'),
  10400: _l('获取应用信息'),

  20000: _l('工作表'),
  20500: _l('获取工作表列表'),
  20400: _l('获取工作表结构信息'),
  20100: _l('创建工作表'),
  20200: _l('编辑工作表'),
  20300: _l('删除工作表'),

  30000: _l('行记录'),
  30100: _l('获取行记录详情'),
  30200: _l('创建行记录'),
  30300: _l('更新行记录'),
  30400: _l('删除行记录'),
  30500: _l('获取行记录列表'),
  30600: _l('批量创建记录'),
  30700: _l('批量更新记录'),
  30800: _l('批量删除记录'),
  30900: _l('获取记录讨论'),
  31000: _l('获取记录日志'),
  31100: _l('获取透视表数据'),
  31200: _l('获取记录关联关系'),
  31300: _l('获取记录分享链接'),

  40000: _l('选项集'),
  40100: _l('创建选项集'),
  40200: _l('删除选项集'),
  40300: _l('获取选项集列表'),
  40400: _l('更新选项集'),

  50000: _l('公共查询'),
  50100: _l('查找部门'),
  50200: _l('查找成员'),
  50300: _l('获取地区信息'),

  60000: _l('角色'),
  60200: _l('获取角色详情'),
  60700: _l('创建角色'),
  60100: _l('删除角色'),
  60300: _l('成员退出所有角色'),
  60400: _l('获取角色列表'),
  60600: _l('角色添加成员'),
  60500: _l('角色移除成员'),

  70000: _l('工作流'),
  70100: _l('获取工作流详情'),
  70200: _l('获取工作流列表'),
  70300: _l('触发工作流'),
  70400: _l('根据表id行id获取审批流程执行列表'),
  70500: _l('获取审批流程执行详情'),

  80000: _l('知识库'),
  80100: _l('获取应用下知识库列表'),
  80200: _l('知识库检索'),
};

export const SCOPE_LIST = [
  {
    code: 10000,
    key: '',
    checked: true,
    children: [
      {
        code: 10100,
        key: 'app:create',
        checked: true,
        children: [],
      },
      {
        code: 10200,
        key: 'app:edit',
        checked: true,
        children: [],
      },
      {
        code: 10300,
        key: 'app:delete',
        checked: true,
        children: [],
      },
      {
        code: 10400,
        key: 'app:get',
        checked: true,
        children: [],
      },
      {
        code: 10500,
        key: 'app:list',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 20000,
    key: '',
    checked: true,
    children: [
      {
        code: 20100,
        key: 'worksheet:create',
        checked: true,
        children: [],
      },
      {
        code: 20200,
        key: 'worksheet:edit',
        checked: true,
        children: [],
      },
      {
        code: 20300,
        key: 'worksheet:delete',
        checked: true,
        children: [],
      },
      {
        code: 20400,
        key: 'worksheet:get',
        checked: true,
        children: [],
      },
      {
        code: 20500,
        key: 'worksheet:list',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 30000,
    key: '',
    checked: true,
    children: [
      {
        code: 30100,
        key: 'record:get',
        checked: true,
        children: [],
      },
      {
        code: 30200,
        key: 'record:create',
        checked: true,
        children: [],
      },
      {
        code: 30300,
        key: 'record:edit',
        checked: true,
        children: [],
      },
      {
        code: 30400,
        key: 'record:delete',
        checked: true,
        children: [],
      },
      {
        code: 30500,
        key: 'record:get_list',
        checked: true,
        children: [],
      },
      {
        code: 30600,
        key: 'record:batch_create',
        checked: true,
        children: [],
      },
      {
        code: 30700,
        key: 'record:batch_update',
        checked: true,
        children: [],
      },
      {
        code: 30800,
        key: 'record:batch_delete',
        checked: true,
        children: [],
      },
      {
        code: 30900,
        key: 'record:get_discussions',
        checked: true,
        children: [],
      },
      {
        code: 31000,
        key: 'record:get_logs',
        checked: true,
        children: [],
      },
      {
        code: 31100,
        key: 'record:get_pivot',
        checked: true,
        children: [],
      },
      {
        code: 31200,
        key: 'record:get_relations',
        checked: true,
        children: [],
      },
      {
        code: 31300,
        key: 'record:get_share_link',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 40000,
    key: '',
    checked: true,
    children: [
      {
        code: 40100,
        key: 'options:create',
        checked: true,
        children: [],
      },
      {
        code: 40200,
        key: 'options:delete',
        checked: true,
        children: [],
      },
      {
        code: 40300,
        key: 'options:list',
        checked: true,
        children: [],
      },
      {
        code: 40400,
        key: 'options:update',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 50000,
    key: '',
    checked: true,
    children: [
      {
        code: 50100,
        key: 'public:find_department',
        checked: true,
        children: [],
      },
      {
        code: 50200,
        key: 'public:find_member',
        checked: true,
        children: [],
      },
      {
        code: 50300,
        key: 'public:get_regions',
        checked: true,
        children: [],
      },
    ],
  },
  {
    code: 60000,
    key: '',
    checked: false,
    children: [
      {
        code: 60100,
        key: 'role:delete',
        checked: false,
        children: [],
      },
      {
        code: 60200,
        key: 'role:get',
        checked: false,
        children: [],
      },
      {
        code: 60300,
        key: 'role:leave_all',
        checked: false,
        children: [],
      },
      {
        code: 60400,
        key: 'role:list',
        checked: false,
        children: [],
      },
      {
        code: 60500,
        key: 'role:remove_member',
        checked: false,
        children: [],
      },
    ],
  },
  {
    code: 70000,
    key: '',
    checked: false,
    children: [
      {
        code: 70100,
        key: 'workflow:get',
        checked: false,
        children: [],
      },
      {
        code: 70200,
        key: 'workflow:list',
        checked: false,
        children: [],
      },
      {
        code: 70300,
        key: 'workflow:trigger',
        checked: false,
        children: [],
      },
      {
        code: 70400,
        key: 'workflow:get_approval_executions',
        checked: false,
        children: [],
      },
    ],
  },
];
