export default {
  开始日期不是日期类型: 'Počáteční datum není platné datum',
  结束日期不是日期类型: 'Koncové datum není platné datum',
  单位不合法: 'Neplatná jednotka',
  '年%04019': 'rok',
  '月%04020': 'měsíc',
  '天%04021': 'den',
  '时%04022': 'hodina',
  '分%04023': 'minuta',
  开始位置不是数字: 'Počáteční pozice není číslo',
  结束位置不是数字: 'Koncová pozice není číslo',
  参数不是数字: 'Parametr není číslo',
  被除数不是数字: 'Dělenec není číslo',
  除数不是数字: 'Dělitel není číslo',
  除数不能为0: 'Dělitel nemůže být 0',
  没有参数: 'Žádné parametry',
  长度太大: 'Délka je příliš velká',
  重复字符不能为空: 'Opakovaný znak nemůže být prázdný',
  天数必须是数字: 'Počet dní musí být číslo',
  日期不是日期类型: 'Hodnota není platné datum',
  总对象数必须是非负整数: 'Celkový počet objektů musí být nezáporné celé číslo',
  选择对象数必须是非负整数: 'Počet vybraných objektů musí být nezáporné celé číslo',
  选择对象数不能大于总对象数: 'Počet vybraných objektů nesmí překročit celkový počet objektů',
};
