export default {
  开始日期不是日期类型: 'Začiatočný dátum nie je platný dátum',
  结束日期不是日期类型: 'Konečný dátum nie je platný dátum',
  单位不合法: 'Neplatná jednotka',
  '年%04019': 'rok',
  '月%04020': 'mesiac',
  '天%04021': 'deň',
  '时%04022': 'hodina',
  '分%04023': 'minúta',
  开始位置不是数字: 'Začiatočná pozícia nie je číslo',
  结束位置不是数字: 'Konečná pozícia nie je číslo',
  参数不是数字: 'Parameter nie je číslo',
  被除数不是数字: 'Delenec nie je číslo',
  除数不是数字: 'Deliteľ nie je číslo',
  除数不能为0: 'Deliteľ nemôže byť 0',
  没有参数: 'Žiadne parametre',
  长度太大: 'Dĺžka je príliš veľká',
  重复字符不能为空: 'Opakovaný znak nemôže byť prázdny',
  天数必须是数字: 'Počet dní musí byť číslo',
  日期不是日期类型: 'Hodnota nie je platný dátum',
  总对象数必须是非负整数: 'Celkový počet objektov musí byť nezáporné celé číslo',
  选择对象数必须是非负整数: 'Počet vybraných objektov musí byť nezáporné celé číslo',
  选择对象数不能大于总对象数: 'Počet vybraných objektov nemôže prekročiť celkový počet objektov',
};
