export default {
  开始日期不是日期类型: 'Start date is not a valid date',
  结束日期不是日期类型: 'End date is not a valid date',
  单位不合法: 'Invalid unit',
  '年%04019': 'year',
  '月%04020': 'month',
  '天%04021': 'day',
  '时%04022': 'hour',
  '分%04023': 'minute',
  开始位置不是数字: 'Start position is not a number',
  结束位置不是数字: 'End position is not a number',
  参数不是数字: 'Parameter is not a number',
  被除数不是数字: 'Dividend is not a number',
  除数不是数字: 'Divisor is not a number',
  除数不能为0: 'Divisor cannot be 0',
  没有参数: 'No parameters',
  长度太大: 'Length is too large',
  重复字符不能为空: 'Repeated character cannot be empty',
  天数必须是数字: 'The number of days must be a number',
  日期不是日期类型: 'Value is not a valid date',
  总对象数必须是非负整数: 'Total number of objects must be a non-negative integer',
  选择对象数必须是非负整数: 'Number of selected objects must be a non-negative integer',
  选择对象数不能大于总对象数: 'Number of selected objects cannot exceed total number of objects',
};
