export default {
  开始日期不是日期类型: "Begindatum is nie 'n geldige datum nie",
  结束日期不是日期类型: "Einddatum is nie 'n geldige datum nie",
  单位不合法: 'Ongeldige eenheid',
  '年%04019': 'jaar',
  '月%04020': 'maand',
  '天%04021': 'dag',
  '时%04022': 'uur',
  '分%04023': 'minuut',
  开始位置不是数字: "Beginposisie is nie 'n nommer nie",
  结束位置不是数字: "Eindposisie is nie 'n nommer nie",
  参数不是数字: "Parameter is nie 'n nommer nie",
  被除数不是数字: "Deeltal is nie 'n nommer nie",
  除数不是数字: "Deler is nie 'n nommer nie",
  除数不能为0: 'Deler kan nie 0 wees nie',
  没有参数: 'Geen parameters nie',
  长度太大: 'Lengte is te groot',
  重复字符不能为空: 'Herhalende karakter kan nie leeg wees nie',
  天数必须是数字: "Die aantal dae moet 'n nommer wees",
  日期不是日期类型: "Waarde is nie 'n geldige datum nie",
  总对象数必须是非负整数: "Totale aantal voorwerpe moet 'n nie-negatiewe heelgetal wees",
  选择对象数必须是非负整数: "Aantal gekose voorwerpe moet 'n nie-negatiewe heelgetal wees",
  选择对象数不能大于总对象数: 'Aantal gekose voorwerpe kan nie totale aantal voorwerpe oorskry nie',
};
