export const QUOTA_LIST_CONTENT = [
  {
    type: 'rowLimit',
    title: _l('工作表行记录'),
    desc: _l('设置每个工作表行记录数量上限'),
    quotaUnit: _l('千行 / 每个表'),
    extraSetting: _l('个工作表'),
    businessType: 2,
    globalDesc: _l('每个工作表行记录数量上限'),
    globalUnit: _l('千行'),
    columns: [
      { title: _l('工作表'), dataIndex: 'worksheet', className: 'flex' },
      { title: _l('所属应用'), dataIndex: 'app', className: 'flex' },
      { title: _l('添加时间'), dataIndex: 'createTime', width: 185 },
      { title: _l('添加人'), dataIndex: 'user', width: 185 },
      {
        title: _l('工作表行记录数量上限'),
        dataIndex: 'size',
        className: 'alignItemsCenter',
        width: 185,
        unit: _l('千行'),
      },
      { title: '', dataIndex: 'action', width: 95 },
    ],
  },
  {
    type: 'workflowLimit',
    title: _l('工作流执行数'),
    desc: _l('设置一天内每个应用的工作流执行次数上限'),
    quotaUnit: _l('千次 / 每个应用 / 每日'),
    extraSetting: _l('个应用'),
    businessType: 4,
    globalDesc: _l('每个应用每日工作流执行次数上限'),
    globalUnit: _l('千次 / 每日'),
    columns: [
      { title: _l('应用'), dataIndex: 'app', className: 'flex' },
      { title: _l('添加时间'), dataIndex: 'createTime', width: 185 },
      { title: _l('添加人'), dataIndex: 'user', width: 185 },
      {
        title: _l('每日工作流执行次数上限'),
        dataIndex: 'size',
        className: 'alignItemsCenter',
        width: 215,
        unit: _l('千次 / 每日'),
      },
      { title: '', dataIndex: 'action', width: 95 },
    ],
  },
  {
    type: 'attachmentLimit',
    title: _l('附件上传总量'),
    desc: _l('设置应用中工作表附件字段、讨论附件，上传量的上限'),
    quotaUnit: _l('GB / 每个应用'),
    extraSetting: _l('个应用'),
    businessType: 3,
    globalDesc: _l('每个应用附件上传量上限'),
    globalUnit: 'GB',
    columns: [
      { title: _l('应用'), dataIndex: 'app', className: 'flex' },
      { title: _l('添加时间'), dataIndex: 'createTime', width: 185 },
      { title: _l('添加人'), dataIndex: 'user', width: 185 },
      { title: _l('附件上传总量'), dataIndex: 'size', className: 'alignItemsCenter', width: 185, unit: 'GB' },
      { title: '', dataIndex: 'action', width: 95 },
    ],
  },
  {
    type: 'attachmentSingleLimit',
    title: _l('附件大小'),
    subTitle: _l('附件大小'),
    desc: _l('设置应用中工作表附件字段、讨论所上传的单个文件大小上限'),
    quotaUnit: _l('MB / 单个文件'),
    extraSetting: _l('个应用'),
    businessType: 1,
    globalDesc: _l('单个附件大小'),
    globalUnit: 'MB',
    columns: [
      { title: _l('应用'), dataIndex: 'app', className: 'flex' },
      { title: _l('添加时间'), dataIndex: 'createTime', width: 185 },
      { title: _l('添加人'), dataIndex: 'user', width: 185 },
      { title: _l('单个附件大小'), dataIndex: 'size', className: 'alignItemsCenter', width: 185, unit: 'MB' },
      { title: '', dataIndex: 'action', width: 95 },
    ],
  },
];

export const TYPE_OBJ = { 1: 'attachmentSingleLimit', 2: 'rowLimit', 3: 'attachmentLimit', 4: 'workflowLimit' };
