export default {
  开始日期不是日期类型: 'Data początkowa nie jest prawidłową datą',
  结束日期不是日期类型: 'Data końcowa nie jest prawidłową datą',
  单位不合法: 'Nieprawidłowa jednostka',
  '年%04019': 'rok',
  '月%04020': 'miesiąc',
  '天%04021': 'dzień',
  '时%04022': 'godzina',
  '分%04023': 'minuta',
  开始位置不是数字: 'Pozycja początkowa nie jest liczbą',
  结束位置不是数字: 'Pozycja końcowa nie jest liczbą',
  参数不是数字: 'Parametr nie jest liczbą',
  被除数不是数字: 'Dzielna nie jest liczbą',
  除数不是数字: 'Dzielnik nie jest liczbą',
  除数不能为0: 'Dzielnik nie może być 0',
  没有参数: 'Brak parametrów',
  长度太大: 'Długość jest zbyt duża',
  重复字符不能为空: 'Powtarzający się znak nie może być pusty',
  天数必须是数字: 'Liczba dni musi być liczbą',
  日期不是日期类型: 'Wartość nie jest prawidłową datą',
  总对象数必须是非负整数: 'Całkowita liczba obiektów musi być nieujemną liczbą całkowitą',
  选择对象数必须是非负整数: 'Liczba wybranych obiektów musi być nieujemną liczbą całkowitą',
  选择对象数不能大于总对象数: 'Liczba wybranych obiektów nie może przekraczać całkowitej liczby obiektów',
};
