export default {
  开始日期不是日期类型: 'La data di inizio non è una data valida',
  结束日期不是日期类型: 'La data di fine non è una data valida',
  单位不合法: 'Unità non valida',
  '年%04019': 'anno',
  '月%04020': 'mese',
  '天%04021': 'giorno',
  '时%04022': 'ora',
  '分%04023': 'minuto',
  开始位置不是数字: 'La posizione iniziale non è un numero',
  结束位置不是数字: 'La posizione finale non è un numero',
  参数不是数字: 'Il parametro non è un numero',
  被除数不是数字: 'Il dividendo non è un numero',
  除数不是数字: 'Il divisore non è un numero',
  除数不能为0: 'Il divisore non può essere 0',
  没有参数: 'Nessun parametro',
  长度太大: 'La lunghezza è troppo grande',
  重复字符不能为空: 'Il carattere ripetuto non può essere vuoto',
  天数必须是数字: 'Il numero di giorni deve essere un numero',
  日期不是日期类型: 'Il valore non è una data valida',
  总对象数必须是非负整数: 'Il numero totale di oggetti deve essere un intero non negativo',
  选择对象数必须是非负整数: 'Il numero di oggetti selezionati deve essere un intero non negativo',
  选择对象数不能大于总对象数: 'Il numero di oggetti selezionati non può superare il numero totale di oggetti',
};
