export default {
  开始日期不是日期类型: 'Startdatum är inte ett giltigt datum',
  结束日期不是日期类型: 'Slutdatum är inte ett giltigt datum',
  单位不合法: 'Ogiltig enhet',
  '年%04019': 'år',
  '月%04020': 'månad',
  '天%04021': 'dag',
  '时%04022': 'timme',
  '分%04023': 'minut',
  开始位置不是数字: 'Startposition är inte ett tal',
  结束位置不是数字: 'Slutposition är inte ett tal',
  参数不是数字: 'Parameter är inte ett tal',
  被除数不是数字: 'Dividenden är inte ett tal',
  除数不是数字: 'Divisorn är inte ett tal',
  除数不能为0: 'Divisorn kan inte vara 0',
  没有参数: 'Inga parametrar',
  长度太大: 'Längden är för stor',
  重复字符不能为空: 'Upprepat tecken kan inte vara tomt',
  天数必须是数字: 'Antalet dagar måste vara ett tal',
  日期不是日期类型: 'Värdet är inte ett giltigt datum',
  总对象数必须是非负整数: 'Det totala antalet objekt måste vara ett icke-negativt heltal',
  选择对象数必须是非负整数: 'Antalet valda objekt måste vara ett icke-negativt heltal',
  选择对象数不能大于总对象数: 'Antalet valda objekt får inte överstiga det totala antalet objekt',
};
