export default {
  开始日期不是日期类型: 'La fecha de inicio no es una fecha válida',
  结束日期不是日期类型: 'La fecha de fin no es una fecha válida',
  单位不合法: 'Unidad no válida',
  '年%04019': 'año',
  '月%04020': 'mes',
  '天%04021': 'día',
  '时%04022': 'hora',
  '分%04023': 'minuto',
  开始位置不是数字: 'La posición inicial no es un número',
  结束位置不是数字: 'La posición final no es un número',
  参数不是数字: 'El parámetro no es un número',
  被除数不是数字: 'El dividendo no es un número',
  除数不是数字: 'El divisor no es un número',
  除数不能为0: 'El divisor no puede ser 0',
  没有参数: 'Sin parámetros',
  长度太大: 'La longitud es demasiado grande',
  重复字符不能为空: 'El carácter de repetición no puede estar vacío',
  天数必须是数字: 'El número de días debe ser un número',
  日期不是日期类型: 'El valor no es una fecha válida',
  总对象数必须是非负整数: 'El número total de objetos debe ser un entero no negativo',
  选择对象数必须是非负整数: 'El número de objetos seleccionados debe ser un entero no negativo',
  选择对象数不能大于总对象数: 'El número de objetos seleccionados no puede exceder el número total de objetos',
};
