export default {
  开始日期不是日期类型: 'Pradžios data nėra galiojanti data',
  结束日期不是日期类型: 'Pabaigos data nėra galiojanti data',
  单位不合法: 'Netinkamas vienetas',
  '年%04019': 'metai',
  '月%04020': 'mėnuo',
  '天%04021': 'diena',
  '时%04022': 'valanda',
  '分%04023': 'minutė',
  开始位置不是数字: 'Pradžios pozicija nėra skaičius',
  结束位置不是数字: 'Pabaigos pozicija nėra skaičius',
  参数不是数字: 'Parametras nėra skaičius',
  被除数不是数字: 'Dalinys nėra skaičius',
  除数不是数字: 'Daliklis nėra skaičius',
  除数不能为0: 'Daliklis negali būti 0',
  没有参数: 'Nėra parametrų',
  长度太大: 'Ilgis per didelis',
  重复字符不能为空: 'Pasikartojantis simbolis negali būti tuščias',
  天数必须是数字: 'Dienų skaičius turi būti skaičius',
  日期不是日期类型: 'Reikšmė nėra galiojanti data',
  总对象数必须是非负整数: 'Bendras objektų skaičius turi būti neneigiamas sveikasis skaičius',
  选择对象数必须是非负整数: 'Pasirinktų objektų skaičius turi būti neneigiamas sveikasis skaičius',
  选择对象数不能大于总对象数: 'Pasirinktų objektų skaičius negali viršyti bendro objektų skaičiaus',
};
