export default {
  开始日期不是日期类型: 'Tarikh mula bukan tarikh yang sah',
  结束日期不是日期类型: 'Tarikh akhir bukan tarikh yang sah',
  单位不合法: 'Unit tidak sah',
  '年%04019': 'tahun',
  '月%04020': 'bulan',
  '天%04021': 'hari',
  '时%04022': 'jam',
  '分%04023': 'minit',
  开始位置不是数字: 'Kedudukan mula bukan nombor',
  结束位置不是数字: 'Kedudukan akhir bukan nombor',
  参数不是数字: 'Parameter bukan nombor',
  被除数不是数字: 'Pembahagi bukan nombor',
  除数不是数字: 'Pembahagi bukan nombor',
  除数不能为0: 'Pembahagi tidak boleh 0',
  没有参数: 'Tiada parameter',
  长度太大: 'Panjang terlalu besar',
  重复字符不能为空: 'Aksara berulang tidak boleh kosong',
  天数必须是数字: 'Bilangan hari mestilah nombor',
  日期不是日期类型: 'Nilai bukan tarikh yang sah',
  总对象数必须是非负整数: 'Jumlah objek mestilah integer bukan negatif',
  选择对象数必须是非负整数: 'Bilangan objek yang dipilih mestilah integer bukan negatif',
  选择对象数不能大于总对象数: 'Bilangan objek yang dipilih tidak boleh melebihi jumlah objek',
};
