export default {
  tag: {
    fontSize: 13,
    fontFamily:
      '"Helvetica Neue", Helvetica, Arial, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif',
    color: '#151515',
    lineHeight: 1.5,
  },
  p: {
    fontFamily:
      '"Helvetica Neue", Helvetica, Arial, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "WenQuanYi Micro Hei", sans-serif',
    color: '#151515',
    lineHeight: 1.5,
  },
  img: {
    border: 'none',
  },
  TxtLeft: {
    textAlign: 'left',
  },
  flexRow: {
    display: 'flex',
    minWidth: 0,
  },

  clear: { clear: 'both', visibility: 'hidden', borderTop: 0, marginTop: -1 },

  Font15: { fontSize: 15 },

  mBottom10: {
    marginBottom: 10,
  },

  table: {
    border: 'none',
    borderCollapse: 'collapse',
    listStyle: 'none',
    width: '100%',
    margin: '0',
    padding: '0',
  },
  companyName: {
    textAlign: 'center',
    fontSize: '13px',
    fontWeight: 'normal',
    color: '#000',
  },
  titleContent: {
    display: 'flex',
    verticalAlign: 'middle',
    height: 80,
    marginBottom: 25,
  },
  reqTitle: {
    fontSize: 22,
    width: 280,
    verticalAlign: 'middle',
    textAlign: 'center',
    fontWeight: 'bold',
    margin: '8px 0',
    lineHeight: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 64,
    whiteSpace: 'break-spaces',
  },
  createBy_h6: {
    fontWeight: 'bold',
    margin: 0,
  },
  sysBox_span: {
    display: 'inline-block',
    width: '50%',
    verticalAlign: 'top',
  },
  sysBox1_span: {
    display: 'block',
  },
  sysBox2_span: {
    display: 'inline-block',
    width: '50%',
  },
  sysBox3_span: {
    display: 'inline-block',
    width: '33.33%',
    textAlign: 'center',
  },
  sysBox_span_common: {
    marginBottom: 10,
  },
  listControls: {
    marginTop: 18,
    overflow: 'hidden',
    width: '100%',
  },
  controlDiv: {
    width: '100%',
    boxSizing: 'border-box',
    overflowX: 'hidden',
  },
  splitLine_title: {
    paddingTop: 24,
    fontSize: 15,
    fontWeight: 'bold',
    paddingLeft: 0,
  },
  controlDiv_span: {
    padding: '5px 0',
    lineHeight: 1.5,
    verticalAlign: 'top',
  },
  controlDiv_span_value: {
    paddingLeft: 10,
    paddingRight: 10,
    boxSizing: 'border-box',
    whiteSpace: 'pre-wrap',
  },
  controlDiv_span_title: {
    paddingLeft: 5,
    // width: 78,
    boxSizing: 'border-box',
    verticalAlign: 'top',
  },
  relationsTitle: {
    marginTop: 24,
    borderBottom: '0.1px solid #ddd',
    paddingBottom: 10,
    lineHeight: '24px',
    fontWeight: 'bold',
  },
  pRelations: {
    borderBottom: 'none',
    marginBottom: 0,
  },
  relations_Ul_Li: {
    border: '0.1px solid #bdbdbd',
    height: 24,
    padding: '0 14px',
    lineHeight: '24px',
    display: 'inline-block',
    color: '#bdbdbd',
    cursor: 'pointer',
    fontWeight: 'normal',
    marginLeft: -1,
    zIndex: 0,
    position: 'relative',
  },
  relations_Ul_Li_Current: {
    border: '0.1px solid #1677ff',
    color: '#1677ff',
    zIndex: 1,
  },
  relationsList_listCon_h5: {
    paddingTop: 5,
    paddingLeft: 5,
    fontWeight: 'normal',
    color: '#000',
  },
  relationsListLi_title: {
    paddingLeft: 5,
    display: 'inline-block',
    width: 78,
    boxSizing: 'border-box',
    verticalAlign: 'top',
  },
  relationsListLi_value: {
    display: 'inline-block',
    paddingLeft: 10,
    paddingRight: 10,
    boxSizing: 'border-box',
    width: 650,
    whiteSpace: 'pre-wrap',
  },
  worksTable_workPersons_th: {
    height: 26,
    border: '0.1px solid #ddd',
    borderRight: 0,
    padding: 5,
    fontWeight: 'normal',
  },
  worksTable_workPersons_td: {
    border: '0.1px solid #ddd',
    borderRight: 0,
    borderTop: 0,
    height: 26,
    padding: 5,
    boxSizing: 'border-box',
  },
  worksTable_workPersons_infoSignature: {
    height: 45,
    backgroundColor: '#fff',
    backgroundRepeat: 'no-repeat',
    backgroundSize: 'contain',
    backgroundPosition: 'center',
  },
  signatureContentWrapper: {
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    width: 700,
    marginLeft: 'auto',
  },
  relationPrintTable: {
    tableLayout: 'auto',
    borderTop: '0.1px solid #ddd',
    borderBottom: 'none',
    borderLeft: 'none',
    borderRadius: 0,
    borderRight: 'none',
    borderCollapse: 'separate',
    borderSpacing: 0,
    width: '100%',
    fontSize: '12px',
    fontFeatureSettings: 'tnum',
    background: '#fff',
    boxSizing: 'border-box',
    color: '#000',
    fontVariant: 'tabular-nums',
    lineHeight: 1.5715,
    listStyle: 'none',
    margin: 0,
    padding: 0,
    position: 'relative',
    marginBottom: '24px',
  },
  relationPrintTable_Tr_Td: {
    border: '0.1px solid #ddd',
    padding: '5px',
    borderRight: 'none',
    borderTop: 'none',
    color: '#000',
    fontWeight: 400,
    whiteSpace: 'pre-wrap',
  },
  relationPrintTable_Tr_Th: {
    border: '0.1px solid #ddd',
    padding: '0',
    borderRight: 'none',
    borderTop: 'none',
    color: '#000',
    fontWeight: 400,
    whiteSpace: 'pre-wrap',
    background: '#fafafa',
  },
  fromName: {
    fontSize: 24,
    color: '#151515',
    fontWeight: 'bold',
    margin: '10px 0 0 0',
  },
  sysField: {
    margin: '16px 0 0 0',
    padding: 0,
    lineHeight: 1.5,
  },
};
