export default {
  开始日期不是日期类型: 'Alguskuupäev ei ole kehtiv kuupäev',
  结束日期不是日期类型: 'Lõppkuupäev ei ole kehtiv kuupäev',
  单位不合法: 'Vigane ühik',
  '年%04019': 'aasta',
  '月%04020': 'kuu',
  '天%04021': 'päev',
  '时%04022': 'tund',
  '分%04023': 'minut',
  开始位置不是数字: 'Algpositsioon ei ole number',
  结束位置不是数字: 'Lõpppositsioon ei ole number',
  参数不是数字: 'Parameeter ei ole number',
  被除数不是数字: 'Jagatav ei ole number',
  除数不是数字: 'Jagaja ei ole number',
  除数不能为0: 'Jagaja ei tohi olla 0',
  没有参数: 'Parameetrid puuduvad',
  长度太大: 'Pikkus on liiga suur',
  重复字符不能为空: 'Korduv märk ei tohi olla tühi',
  天数必须是数字: 'Päevade arv peab olema number',
  日期不是日期类型: 'Väärtus ei ole kehtiv kuupäev',
  总对象数必须是非负整数: 'Objektide koguarv peab olema mittenegatiivne täisarv',
  选择对象数必须是非负整数: 'Valitud objektide arv peab olema mittenegatiivne täisarv',
  选择对象数不能大于总对象数: 'Valitud objektide arv ei tohi ületada objektide koguarvu',
};
