export default {
  开始日期不是日期类型: 'Ang petsa ng pagsisimula ay hindi wastong petsa',
  结束日期不是日期类型: 'Ang petsa ng pagtatapos ay hindi wastong petsa',
  单位不合法: 'Hindi wastong yunit',
  '年%04019': 'taon',
  '月%04020': 'buwan',
  '天%04021': 'araw',
  '时%04022': 'oras',
  '分%04023': 'minuto',
  开始位置不是数字: 'Ang panimulang posisyon ay hindi numero',
  结束位置不是数字: 'Ang panghuling posisyon ay hindi numero',
  参数不是数字: 'Ang parameter ay hindi numero',
  被除数不是数字: 'Ang dibidendo ay hindi numero',
  除数不是数字: 'Ang divisor ay hindi numero',
  除数不能为0: 'Ang divisor ay hindi pwedeng 0',
  没有参数: 'Walang parameter',
  长度太大: 'Sobrang laki ng haba',
  重复字符不能为空: 'Hindi pwedeng walang laman ang inuulit na karakter',
  天数必须是数字: 'Ang bilang ng araw ay dapat numero',
  日期不是日期类型: 'Ang halaga ay hindi wastong petsa',
  总对象数必须是非负整数: 'Ang kabuuang bilang ng mga bagay ay dapat na hindi negatibong integer',
  选择对象数必须是非负整数: 'Ang bilang ng mga napiling bagay ay dapat na hindi negatibong integer',
  选择对象数不能大于总对象数:
    'Ang bilang ng mga napiling bagay ay hindi maaaring lumampas sa kabuuang bilang ng mga bagay',
};
