export default {
  开始日期不是日期类型: 'Das Startdatum ist kein gültiges Datum',
  结束日期不是日期类型: 'Das Enddatum ist kein gültiges Datum',
  单位不合法: 'Ungültige Einheit',
  '年%04019': 'Jahr',
  '月%04020': 'Monat',
  '天%04021': 'Tag',
  '时%04022': 'Stunde',
  '分%04023': 'Minute',
  开始位置不是数字: 'Die Startposition ist keine Zahl',
  结束位置不是数字: 'Die Endposition ist keine Zahl',
  参数不是数字: 'Der Parameter ist keine Zahl',
  被除数不是数字: 'Der Dividend ist keine Zahl',
  除数不是数字: 'Der Divisor ist keine Zahl',
  除数不能为0: 'Der Divisor darf nicht 0 sein',
  没有参数: 'Keine Parameter',
  长度太大: 'Die Länge ist zu groß',
  重复字符不能为空: 'Das Wiederholungszeichen darf nicht leer sein',
  天数必须是数字: 'Die Anzahl der Tage muss eine Zahl sein',
  日期不是日期类型: 'Der Wert ist kein gültiges Datum',
  总对象数必须是非负整数: 'Die Gesamtzahl der Objekte muss eine nicht negative Ganzzahl sein',
  选择对象数必须是非负整数: 'Die Anzahl der ausgewählten Objekte muss eine nicht negative Ganzzahl sein',
  选择对象数不能大于总对象数: 'Die Anzahl der ausgewählten Objekte darf die Gesamtzahl der Objekte nicht überschreiten',
};
