export default {
  开始日期不是日期类型: 'Begindatum is geen geldige datum',
  结束日期不是日期类型: 'Einddatum is geen geldige datum',
  单位不合法: 'Ongeldige eenheid',
  '年%04019': 'jaar',
  '月%04020': 'maand',
  '天%04021': 'dag',
  '时%04022': 'uur',
  '分%04023': 'minuut',
  开始位置不是数字: 'Beginpositie is geen getal',
  结束位置不是数字: 'Eindpositie is geen getal',
  参数不是数字: 'Parameter is geen getal',
  被除数不是数字: 'Deeltal is geen getal',
  除数不是数字: 'Deler is geen getal',
  除数不能为0: 'Deler kan niet 0 zijn',
  没有参数: 'Geen parameters',
  长度太大: 'Lengte is te groot',
  重复字符不能为空: 'Herhalend teken kan niet leeg zijn',
  天数必须是数字: 'Het aantal dagen moet een getal zijn',
  日期不是日期类型: 'Waarde is geen geldige datum',
  总对象数必须是非负整数: 'Het totale aantal objecten moet een niet-negatief geheel getal zijn',
  选择对象数必须是非负整数: 'Het aantal geselecteerde objecten moet een niet-negatief geheel getal zijn',
  选择对象数不能大于总对象数: 'Het aantal geselecteerde objecten mag het totale aantal objecten niet overschrijden',
};
