export const DRAG_ITEMS = {
  LIST_ITEM: 'LIST_ITEM',
  DISPLAY_ITEM: 'DISPLAY_ITEM',
};

export const WHOLE_SIZE = 12;

export const TEMP_WIDGET = 'TEMP_WIDGET';

export const DRAG_MODE = {
  INSERT_NEW_LINE: 'INSERT_NEW_LINE',
  INSERT_TO_COL: 'INSERT_TO_COL',
  INSERT_TO_ROW_END: 'INSERT_TO_ROW_END',
  INSERT_ROW: 'INSERT_ROW',
};

export const DRAG_DISTANCE = {
  VERTICAL: 16,
};
