export default {
  开始日期不是日期类型: 'Aloituspäivä ei ole kelvollinen päivämäärä',
  结束日期不是日期类型: 'Lopetuspäivä ei ole kelvollinen päivämäärä',
  单位不合法: 'Virheellinen yksikkö',
  '年%04019': 'vuosi',
  '月%04020': 'kuukausi',
  '天%04021': 'päivä',
  '时%04022': 'tunti',
  '分%04023': 'minuutti',
  开始位置不是数字: 'Aloituspaikka ei ole numero',
  结束位置不是数字: 'Lopetuspaikka ei ole numero',
  参数不是数字: 'Parametri ei ole numero',
  被除数不是数字: 'Jaettava ei ole numero',
  除数不是数字: 'Jakaja ei ole numero',
  除数不能为0: 'Jakaja ei voi olla 0',
  没有参数: 'Ei parametreja',
  长度太大: 'Pituus on liian suuri',
  重复字符不能为空: 'Toistuva merkki ei voi olla tyhjä',
  天数必须是数字: 'Päivien lukumäärän on oltava numero',
  日期不是日期类型: 'Arvo ei ole kelvollinen päivämäärä',
  总对象数必须是非负整数: 'Kohteiden kokonaismäärän on oltava ei-negatiivinen kokonaisluku',
  选择对象数必须是非负整数: 'Valittujen kohteiden määrän on oltava ei-negatiivinen kokonaisluku',
  选择对象数不能大于总对象数: 'Valittujen kohteiden määrä ei voi ylittää kohteiden kokonaismäärää',
};
