export default {
  开始日期不是日期类型: 'Data de început nu este o dată validă',
  结束日期不是日期类型: 'Data de sfârșit nu este o dată validă',
  单位不合法: 'Unitate nevalidă',
  '年%04019': 'an',
  '月%04020': 'lună',
  '天%04021': 'zi',
  '时%04022': 'oră',
  '分%04023': 'minut',
  开始位置不是数字: 'Poziția de început nu este un număr',
  结束位置不是数字: 'Poziția de sfârșit nu este un număr',
  参数不是数字: 'Parametrul nu este un număr',
  被除数不是数字: 'Deîmpărțitul nu este un număr',
  除数不是数字: 'Împărțitorul nu este un număr',
  除数不能为0: 'Împărțitorul nu poate fi 0',
  没有参数: 'Niciun parametru',
  长度太大: 'Lungimea este prea mare',
  重复字符不能为空: 'Caracterul repetat nu poate fi gol',
  天数必须是数字: 'Numărul de zile trebuie să fie un număr',
  日期不是日期类型: 'Valoarea nu este o dată validă',
  总对象数必须是非负整数: 'Numărul total de obiecte trebuie să fie un întreg nenegativ',
  选择对象数必须是非负整数: 'Numărul de obiecte selectate trebuie să fie un întreg nenegativ',
  选择对象数不能大于总对象数: 'Numărul de obiecte selectate nu poate depăși numărul total de obiecte',
};
