export default {
  开始日期不是日期类型: 'Başlangıç tarihi geçerli bir tarih değil',
  结束日期不是日期类型: 'Bitiş tarihi geçerli bir tarih değil',
  单位不合法: 'Geçersiz birim',
  '年%04019': 'yıl',
  '月%04020': 'ay',
  '天%04021': 'gün',
  '时%04022': 'saat',
  '分%04023': 'dakika',
  开始位置不是数字: 'Başlangıç konumu bir sayı değil',
  结束位置不是数字: 'Bitiş konumu bir sayı değil',
  参数不是数字: 'Parametre bir sayı değil',
  被除数不是数字: 'Bölünen bir sayı değil',
  除数不是数字: 'Bölen bir sayı değil',
  除数不能为0: 'Bölen 0 olamaz',
  没有参数: 'Parametre yok',
  长度太大: 'Uzunluk çok büyük',
  重复字符不能为空: 'Tekrarlanan karakter boş olamaz',
  天数必须是数字: 'Gün sayısı bir sayı olmalıdır',
  日期不是日期类型: 'Değer geçerli bir tarih değil',
  总对象数必须是非负整数: 'Toplam nesne sayısı negatif olmayan bir tam sayı olmalıdır',
  选择对象数必须是非负整数: 'Seçilen nesne sayısı negatif olmayan bir tam sayı olmalıdır',
  选择对象数不能大于总对象数: 'Seçilen nesne sayısı toplam nesne sayısını aşamaz',
};
