export default {
  开始日期不是日期类型: 'A kezdő dátum nem érvényes dátum',
  结束日期不是日期类型: 'A befejező dátum nem érvényes dátum',
  单位不合法: 'Érvénytelen egység',
  '年%04019': 'év',
  '月%04020': 'hónap',
  '天%04021': 'nap',
  '时%04022': 'óra',
  '分%04023': 'perc',
  开始位置不是数字: 'A kezdő pozíció nem szám',
  结束位置不是数字: 'A befejező pozíció nem szám',
  参数不是数字: 'A paraméter nem szám',
  被除数不是数字: 'Az osztandó nem szám',
  除数不是数字: 'Az osztó nem szám',
  除数不能为0: 'Az osztó nem lehet 0',
  没有参数: 'Nincsenek paraméterek',
  长度太大: 'A hossz túl nagy',
  重复字符不能为空: 'Az ismétlődő karakter nem lehet üres',
  天数必须是数字: 'A napok számának számnak kell lennie',
  日期不是日期类型: 'Az érték nem érvényes dátum',
  总对象数必须是非负整数: 'Az objektumok teljes számának nem negatív egész számnak kell lennie',
  选择对象数必须是非负整数: 'A kiválasztott objektumok számának nem negatív egész számnak kell lennie',
  选择对象数不能大于总对象数: 'A kiválasztott objektumok száma nem haladhatja meg az objektumok teljes számát',
};
